version: 0.0.1
language: 'nodejs'
variables:
  - token
methods:
  GET:
    status_codes:
      - 200 # Can only have one 2xx status code and it must be first in the list
    query_string_params:
      - token
      - command
      - text
  POST:
    status_codes:
      - 201 # Can only have one 2xx status code and it must be first in the list
      - 400
      - 401
      - 404
      - 500
    query_string_params:
      - token
      - command
      - text
