language: 'nodejs' # nodejs or python
environment: 'master'
endpoint: 'joule'
main-file: 'index'
main-function: 'handler'
variables:
  - key
  - foo
methods:
  GET:
    status_codes:
      - 200 # Can only have one 2xx status code and it must be first in the list
      - 400
      - 401
      - 404
      - 500
  POST:
    status_codes:
      - 201 # Can only have one 2xx status code and it must be first in the list
      - 400
      - 401
      - 404
      - 500
  PUT:
    status_codes:
      - 204
